# Generated by Django 6.0 on 2025-12-21 11:21

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('youtube_title', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('audio_dir', models.CharField(blank=True, max_length=512, null=True)),
                ('audio_status', models.CharField(choices=[('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Not Processed', max_length=20)),
                ('audio_data', models.JSONField(blank=True, default=api.models.default_audio_data)),
                ('subtitle_status', models.CharField(choices=[('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Not Processed', max_length=20)),
                ('translation_status', models.CharField(choices=[('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Not Processed', max_length=20)),
                ('pronounce_status', models.CharField(choices=[('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Not Processed', max_length=20)),
            ],
        ),
    ]
