# Generated by Django 5.2.8 on 2025-11-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Processing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_link", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("PROCESSING", "처리 중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "transcript_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("PROCESSING", "처리 중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("transcript", models.TextField(blank=True, null=True)),
                (
                    "ipa_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("PROCESSING", "처리 중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("ipa", models.TextField(blank=True, null=True)),
                (
                    "translate_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("PROCESSING", "처리 중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("translation", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
